#
#@BEGIN LICENSE
#
# mpi_direct_scf by Psi4 Developer, a plugin to:
#
# PSI4: an ab initio quantum chemistry software package
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
#@END LICENSE
#

#
# Plugin Makefile generated by Psi4.
#
# You shouldn't need to modify anything in this file.
#

# The name of your plugin. Taken from the directory name.
NAME = $(shell basename `pwd`)

# C++ source files for your plugin. By default we grab all *.cc files.
CXXSRC = $(notdir $(wildcard *.cc))

# Flags that were used to compile Psi4.
CXX = /opt/apps/intel13_1/mvapich2/1.9a2/bin/mpicxx
CXXDEFS = -DFC_SYMBOL=2 -DHAVE_MPI -DHAVE_MKL_LAPACK -DHAVE_MKL_BLAS -DSYS_LINUX
CXXFLAGS = -DRESTRICT=__restrict__ -Xlinker -export-dynamic -fPIC -std=gnu++98 -openmp      -O3 -no-prec-div -DNDEBUG -xHost
LDFLAGS = -shared-intel -shared-intel
INCLUDES = -I/home/akumar1/src/parallel_psi4/psi4/obj/src/lib -I/home/akumar1/src/parallel_psi4/psi4/src/lib -I/home/akumar1/src/parallel_psi4/psi4/include -I/home/akumar1/src/parallel_psi4/psi4/obj/include -I/home/akumar1/src/parallel_psi4/psi4/obj/boost/include -I/opt/apps/intel13_1/python/2.7.2/include/python2.7 -I/usr/include -I/usr/include -I/opt/apps/intel/13.1/compiler/include -I/usr/include -I/opt/apps/intel13_1/mvapich2/1.9a2/include
OBJDIR = /home/akumar1/src/parallel_psi4/psi4/obj

# Used to determine linking flags.
UNAME = $(shell uname)

# Need to link against Psi4 plugin library
PSIPLUGIN = -L$(OBJDIR)/lib -lplugin

DEPENDINCLUDE = $(notdir $(wildcard *.h*))

PSITARGET = $(NAME).so

# Start the compilation rules
default:: $(PSITARGET)

# Add the flags needed for shared library creation
ifeq ($(UNAME), Linux)
    LDFLAGS += -shared
endif
ifeq ($(UNAME), Darwin)
    LDFLAGS += -shared -undefined dynamic_lookup
    CXXFLAGS += -fno-common
endif

# The object files
BINOBJ = $(CXXSRC:%.cc=%.o)

%.o: %.cc
	$(CXX) $(CXXDEFS) $(CXXFLAGS) $(INCLUDES) -c $<

$(PSITARGET): $(BINOBJ)
	$(CXX) $(LDFLAGS) -o $@ $^ $(CXXDEFS) $(PSIPLUGIN)

# Erase all compiled intermediate files
clean:
	rm -f $(BINOBJ) $(PSITARGET) *.d *.pyc *.test output.dat psi.timer.dat

